name: Cron Job

on:
    schedule:
        - cron: "not valid to not get scheduled"

jobs:
    cron:
        runs-on: ubuntu-latest

        steps:
            - name: Hello World!
              run: echo "Hello World!"
